
spring.datasource.url=jdbc:${URL_DATABASE}?createDatabaseIfNotExist=true
spring.datasource.username=${USER_DATABASE}
spring.datasource.password=${PASS_DATABASE}


jwt.secret=${JWT_SECRET}

jwt.expiration=${JWT_EXP}
jwt.httponly=${JWT_HTTP}
jwt.secure=${JWT_SECURE}

spring.mail.password=${MAIL_PASS}
spring.mail.username=${MAIL_USER}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true